"""Tests for the generation agent and the files it produces.

These run entirely offline: generation is deterministic and uses no language
model, so the whole pipeline can be asserted on directly.
"""

import ast

import pytest

from vibestack.agent import GenerationAgent, Tool
from vibestack.spec import (
    AuthConfig,
    Entity,
    EntityField,
    FieldType,
    ProjectSpec,
    Relationship,
    RelationshipType,
)
from vibestack.workspace import write_workspace


def blog_spec() -> ProjectSpec:
    """A small blog specification used by most of these tests."""
    user = Entity(
        name="User",
        fields=[
            EntityField(name="id", type=FieldType.INTEGER, primary_key=True),
            EntityField(name="email", type=FieldType.STRING, unique=True, nullable=False),
            EntityField(name="created_at", type=FieldType.DATETIME, nullable=False),
        ],
        relationships=[
            Relationship(
                target_entity="Post",
                type=RelationshipType.ONE_TO_MANY,
                back_populates="author",
            )
        ],
    )
    post = Entity(
        name="Post",
        fields=[
            EntityField(name="id", type=FieldType.INTEGER, primary_key=True),
            EntityField(name="title", type=FieldType.STRING, nullable=False),
            EntityField(name="body", type=FieldType.TEXT),
        ],
    )
    return ProjectSpec(
        project_name="blog_api",
        description="A blog API",
        entities=[user, post],
    )


@pytest.fixture
def generated_state():
    """Run the agent once and reuse the result across tests."""
    return GenerationAgent().run(blog_spec())


def test_expected_files_are_generated(generated_state):
    """The core files of a FastAPI project should all be present."""
    expected_files = [
        "app/main.py",
        "app/config.py",
        "app/database.py",
        "app/dependencies.py",
        "app/models/user.py",
        "app/models/post.py",
        "app/schemas/user.py",
        "app/routers/post.py",
        "app/routers/auth.py",
        "app/security.py",
        "pyproject.toml",
        "Dockerfile",
        "docker-compose.yml",
        "README.md",
        "tests/test_health.py",
    ]

    for file_path in expected_files:
        assert file_path in generated_state.generated_files, f"missing {file_path}"


def test_every_generated_python_file_is_valid_syntax(generated_state):
    """Generated Python must parse; this catches broken templates immediately."""
    for file_path, content in generated_state.generated_files.items():
        if not file_path.endswith(".py"):
            continue
        # ast.parse raises SyntaxError if the generated code is malformed.
        ast.parse(content, filename=file_path)


def test_password_hash_never_appears_in_a_schema(generated_state):
    """The stored password hash must not be exposed through the API."""
    user_schema = generated_state.generated_files["app/schemas/user.py"]

    assert "password_hash" not in user_schema
    # The create schema still accepts a plain password, which is hashed on use.
    assert "password: str" in user_schema


def test_model_and_router_agree_on_the_class_name(generated_state):
    """Files generated by different tools must refer to the same class."""
    model = generated_state.generated_files["app/models/post.py"]
    router = generated_state.generated_files["app/routers/post.py"]
    schema = generated_state.generated_files["app/schemas/post.py"]

    assert "class Post(Base):" in model
    assert "from app.models.post import Post" in router
    assert "class PostCreate(PostBase):" in schema


def test_foreign_key_appears_on_the_child_model(generated_state):
    """The one-to-many relationship should place the key on Post."""
    post_model = generated_state.generated_files["app/models/post.py"]

    assert 'ForeignKey("users.id")' in post_model
    assert 'relationship("User", back_populates="posts")' in post_model


def test_every_file_has_a_ledger_entry(generated_state):
    """Each generated file must be explained in the change ledger."""
    explained_paths = {entry.file_path for entry in generated_state.ledger}

    for file_path in generated_state.generated_files:
        assert file_path in explained_paths, f"{file_path} has no ledger entry"

    for entry in generated_state.ledger:
        assert entry.rationale.strip(), "a ledger entry has an empty rationale"


def test_auth_routes_are_skipped_when_auth_is_disabled():
    """Disabling auth should remove the security files entirely."""
    spec = blog_spec()
    spec.auth = AuthConfig(enabled=False)

    state = GenerationAgent().run(spec)

    assert "app/routers/auth.py" not in state.generated_files
    assert "app/security.py" not in state.generated_files
    assert "auth" not in state.generated_files["app/main.py"]


def test_tools_can_be_replaced():
    """The agent runs whatever tools it is given, which keeps it testable."""
    calls: list[str] = []

    def recording_tool(context):
        calls.append("ran")
        context.add_file("note.txt", "hello", "records that the tool ran")

    agent = GenerationAgent(
        tools=[Tool(name="recorder", description="test tool", run=recording_tool)]
    )
    state = agent.run(blog_spec())

    assert calls == ["ran"]
    assert state.generated_files == {"note.txt": "hello"}


def test_write_workspace_creates_files_on_disk(tmp_path, generated_state):
    """Writing the workspace should create every file, including nested ones."""
    written_paths = write_workspace(generated_state, tmp_path)

    assert len(written_paths) == len(generated_state.generated_files)
    assert (tmp_path / "app" / "main.py").is_file()
    assert (tmp_path / "app" / "models" / "user.py").is_file()
    assert (tmp_path / "Dockerfile").is_file()
