"""initial schema

Revision ID: d27b86241359
Revises: 
Create Date: 2026-08-18 06:58:24.222495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd27b86241359'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('progress', sa.Text(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('build_passed', sa.Integer(), nullable=False),
    sa.Column('heal_attempts', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('generated_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_files_job_id'), ['job_id'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entries_job_id'), ['job_id'], unique=False)

    op.create_table('review_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('lens', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_findings_job_id'), ['job_id'], unique=False)

    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_records_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_records_job_id'))

    op.drop_table('usage_records')
    with op.batch_alter_table('review_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_findings_job_id'))

    op.drop_table('review_findings')
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_job_id'))

    op.drop_table('ledger_entries')
    with op.batch_alter_table('generated_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_files_job_id'))

    op.drop_table('generated_files')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_created_at'))

    op.drop_table('jobs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
